export const SECTION_INPUT_MAP: Record<string, string[]> = {
  SubdomainDiscovery: ['Domain'],
  Shodan:             ['IP'],
  Urlscan:            ['Domain'],
  OsintEnrichment:    ['IP', 'Domain'],
  Naabu:              ['IP', 'Subdomain'],
  Masscan:            ['IP'],
  Nmap:               ['IP', 'Port'],
  Httpx:              ['Subdomain', 'IP', 'Port'],
  Katana:             ['BaseURL'],
  Hakrawler:          ['BaseURL'],
  Jsluice:            ['BaseURL', 'Endpoint'],
  Ffuf:               ['BaseURL', 'Endpoint'],
  Gau:                ['Domain', 'Subdomain'],
  ParamSpider:        ['Domain', 'Subdomain'],
  Kiterunner:         ['BaseURL'],
  Arjun:              ['BaseURL', 'Endpoint'],
  Nuclei:             ['BaseURL', 'Endpoint', 'Technology', 'Domain'],
  CveLookup:          ['Technology'],
  GvmScan:            ['IP', 'Port', 'Subdomain', 'Domain'],
  Github:             ['Domain'],
  SecurityChecks:     ['BaseURL', 'IP', 'Subdomain', 'Domain'],
  Uncover:            ['Domain'],
  JsRecon:            ['BaseURL', 'Endpoint'],
  Mitre:              ['CVE'],
}

export const SECTION_NODE_MAP: Record<string, string[]> = {
  SubdomainDiscovery: ['Domain', 'Subdomain', 'IP', 'DNSRecord', 'ExternalDomain'],
  Shodan:             ['IP', 'Port', 'Service', 'Subdomain', 'ExternalDomain', 'DNSRecord', 'Technology', 'Vulnerability', 'CVE'],
  Urlscan:            ['Domain', 'Subdomain', 'ExternalDomain', 'IP', 'Endpoint', 'Parameter'],
  OsintEnrichment:    ['IP', 'Domain', 'Subdomain', 'Port', 'Service', 'ExternalDomain', 'DNSRecord', 'Technology', 'ThreatPulse', 'Malware', 'Certificate', 'Vulnerability', 'CVE'],
  Naabu:              ['Port', 'Service'],
  Masscan:            ['Port', 'Service'],
  Nmap:               ['Port', 'Service', 'Technology', 'Vulnerability', 'CVE'],
  Httpx:              ['BaseURL', 'Certificate', 'Technology', 'Header', 'ExternalDomain'],
  Katana:             ['Endpoint', 'Parameter', 'BaseURL', 'ExternalDomain'],
  Hakrawler:          ['Endpoint', 'Parameter', 'BaseURL', 'ExternalDomain'],
  Jsluice:            ['Endpoint', 'Parameter', 'BaseURL', 'Secret', 'ExternalDomain'],
  Ffuf:               ['Endpoint', 'BaseURL', 'ExternalDomain'],
  Gau:                ['Endpoint', 'Parameter', 'BaseURL', 'ExternalDomain'],
  ParamSpider:        ['Endpoint', 'Parameter', 'BaseURL', 'ExternalDomain'],
  Kiterunner:         ['Endpoint', 'BaseURL'],
  Arjun:              ['Parameter', 'ExternalDomain'],
  Nuclei:             ['Vulnerability', 'Endpoint', 'Parameter', 'CVE', 'MitreData', 'Capec'],
  CveLookup:          ['CVE', 'MitreData', 'Capec'],
  GvmScan:            ['Vulnerability', 'Technology', 'Traceroute', 'Certificate', 'ExploitGvm', 'CVE', 'MitreData', 'Capec'],
  Github:             ['GithubHunt', 'GithubRepository', 'GithubPath', 'GithubSecret', 'GithubSensitiveFile'],
  SecurityChecks:     ['Vulnerability'],
  Uncover:            ['IP', 'Subdomain', 'Port', 'Endpoint'],
  JsRecon:            ['Secret', 'Endpoint', 'Parameter', 'Subdomain', 'ExternalDomain', 'Technology'],
  Mitre:              ['MitreData', 'Capec'],
}
